name: ski_slope
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version: A.B.C+X.
# For Android:
# A.B.C represents the versionName such as 1.0.0.
# X (the number after the +) represents the versionCode such as 1, 2, 3, etc.
#
# For iOS:
# A.B.C represents the CFBundleShortVersionString such as 1.0.0.
# X (the number after the +) represents the CFBundleVersion such as 1, 2, 3, etc.
#
# Do not forget to execute flutter build apk / flutter build ipa or flutter run after this step
version: 1.1.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.4
  bloc_pattern: ^3.0.0+1
  shared_preferences: ^2.0.13
  http: ^0.13.4
  qr_flutter: ^4.0.0
  font_awesome_flutter: ^10.1.0
  webview_flutter: ^3.0.2
  equatable: ^2.0.3
  event_bus: ^2.0.0
  google_sign_in: ^5.3.0
  another_flushbar: ^1.10.28
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0
  build_runner: ^2.1.10

  flutter_lints: ^1.0.4
  intl: ^0.17.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/welcome_screen/
    - assets/login_screen/
