/// Flutter icons VoucherIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  VoucherIcon
///      fonts:
///       - asset: fonts/VoucherIcon.ttf
///
///
///
import 'package:flutter/widgets.dart';

class VoucherIcon {
  VoucherIcon._();

  static const _kFontFam = 'VoucherIcon';
  static const String? _kFontPkg = null;

  static const IconData ski_pass = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
